### PR TITLE
remove yarn dependency, fixes #69

### LINKED ISSUE #69: please remove `yarn` from dependencies
Well you don’t have any `require` statement that explicitly requires yarn. So I think this is most likely a bug :-)

### PR DESCRIPTION
**Pull request by Swatinem**

### CODE REVIEW

**Comment by richardscarrott** [comment]
@Swatinem thanks for the PR, could you re-add yarn as a *devDep* as the CI depends on it, thanks

**Comment by richardscarrott** [comment]
@Swatinem thx, will publish a new version on the weekend

**Comment by Vestride** [comment]
👋 Hi @richardscarrott. If you could publish a new version with this fix, it would be appreciated.

**Comment by dobesv** [comment]
Any chance of publishing this to npm ?

**Comment by richardscarrott** [comment]
Apologies for being so slow with this -- had a busy 6 months -- this is now published in `0.6.0`.

**Pull request merged**
