### PR TITLE
Show a waiting response while webpack compilation is not over

### LINKED ISSUE #27: TypeError: serverRenderer is not a function on initial page load
I was getting an error from the title when I started my server and opened my browser before compilation was finished. After compilation was done, everything started to work perfectly. So it seems that ```webpack-dev-middleware``` didn't put serving responses on hold during code compilation, despite the fact my setup was according to the docs.

What helped me was adding ```serverSideRender: true``` to  ```webpack-dev-middleware```, but it was not mentioned in the docs, that's why I am asking, if anyone experienced similar issue? I yes, I could create a PR to mention this in the docs.

### PR DESCRIPTION
**Pull request by mohsen1**
Fixes #27

### CODE REVIEW

**Comment by mohsen1** [comment]
@richardscarrott  this works great in my own setup. The refresh meta is pretty useful. Do you think you can merge this?

**Comment by richardscarrott** [comment]
@mohsen1 thanks for sending this PR. I like the idea of presenting something to the client whilst webpack is compiling, however I'm not sure if this is the right approach until #27 is fixed because currently, this only works because of that bug...a bug I've not been able to reproduce in any of my own projects yet.

The original design was for `webpack-dev-middleware` to hold on to the request until the compiler has finished so I wonder if this would be better suited directly in `webpack-dev-middleware`?

**Comment by mohsen1** [comment]
@richardscarrott see your repo invitations :) 

That repo will reproduce the error

**Comment by mohsen1** [comment]
I have a hypothesis 
Probably because Awesome-TypeScript-Loader is doing work in a separate process....

**Comment by richardscarrott** [comment]
@mohsen1 I did some investigation into this using @klis87 repo https://github.com/60frames/webpack-hot-server-middleware/issues/27

It turns out #27 is caused by the use of `publicPath`, I'm therefore going to recommend people use `serverSideRender: true` in `webpack-dev-middleware` to ensure this middleware doesn't get the request until the build is stable... which means this PR wouldn't make sense in `webpack-hot-server-middleware`... I think it's something that could be done with some middleware in-between `webpack-dev-middleware` and this, e.g.

```js
app.use(webpackHotServerMiddleware(compiler, {
    publicPath: '/assets/'
}));
app.use(() => {
     let isCompiling = true;
    compiler.plugin("done", () => isCompiling = false);
    compiler.plugin("compile", () => isCompiling = true); // Not 100% sure exactly which phase(s) you'd need to hook into...
return (req, res, next) => isCompiling ? res.send('compiling...') : next();
}());
app.use(webpackHotServerMiddleware(compiler));
```

**Comment by mohsen1** [comment]
Thanks a lot for looking into this! `serverSideRender: true` does the trick in my project as well. 

Closing as this change is not required.

**Pull request closed without merging**
