### PR TITLE
Add missing second argument to koaDevware

### LINKED ISSUE #45: Koa example throws an error for plugin of undefined
```
new Promise((resolve, reject) => {
      dev.waitUntilValid(() => resolve(true));
      compiler.plugin('failed', error => reject(error));
    });
```

This is because compiler is not passed into the example middleware

### PR DESCRIPTION
**Pull request by roastlechon**
Fixes #45

### CODE REVIEW

**Comment by richardscarrott** [comment]
@roastlechon well caught, not sure why this didn't throw an error when I tested it.

Do you or @pho3nixf1re know whether we can use something like [`koa-connect`](https://www.npmjs.com/package/koa-connect) or [`express-to-koa`](https://www.npmjs.com/package/express-to-koa) instead of this custom wrapper?

**Comment by roastlechon** [comment]
I think the wrapper just prevents the middleware from continuing until the bundle is finished compiling. This is so that it doesnt throw an error about serverRenderer is undefined.

**Comment by pho3nixf1re** [comment]
That is correct @roastlechon . I modeled my wrapper after [koa-webpack](https://github.com/shellscape/koa-webpack) because their implementation did not allow splitting the client and server compilers and to allow waiting for them separately. I used a simplified version of the same wrapper I use in my own stack in this example.

**Comment by roastlechon** [comment]
I was using koa-webpack, but when I saw your example, I jumped ship immediately and found the bug with the example! :D thanks for the good work

**Pull request merged**
